project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Min Lin's Homepage"
  search: true
  cookie-consent: false
  open-graph: true
  site-url: https://<yourwebsite>.github.io
  navbar:
    right:
      - blog.qmd

format:
  html:
    theme: 
    - minty
    css: styles.css
