project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Min Lin"
  search: true
  cookie-consent: false
  twitter-card: true
  open-graph: true
  site-url: https://<yourwebsite>.github.io
  navbar:
    right:
      - blog.qmd
      - misc.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  page-footer: 
    left: "You can write somethig here too."

format:
  html:
    theme: 
    - minty
    css: styles.css
